### ISSUE TITLE
Code review Therapy/index.html

### ISSUE THREAD

**Issue by pashkes** [Shvarts91/site#1]
1. Помимо основного шрифта, рекомендуют указывать альтернативный максимально похожий на кастомный на случай если кастомный шрифт не загрузился либо  занимает много времени. Еще в конце обычно указывают тип шрифта `serif` или `sans-serif`
https://github.com/Shvarts91/site/blob/af2454b53f51e512440046283c657fc907eb3741/Attorneyster/index.html#L62

2. Достаточно было просто `ul` Не забывай о весе селекторов
https://github.com/Shvarts91/site/blob/af2454b53f51e512440046283c657fc907eb3741/Attorneyster/index.html#L82-L84

### Oбщие рекомендации:
1. Удобно когда свойства идут в группированном порядке
https://github.com/Shvarts91/site/blob/af2454b53f51e512440046283c657fc907eb3741/Attorneyster/index.html#L96-L102
Пример:
```css
.selector {
  /* Positioning */
  position: absolute;
  z-index: 10;
  top: 0;
  right: 0;

  /* Display & Box Model */
  display: inline-block;
  overflow: hidden;
  box-sizing: border-box;
  width: 100px;
  height: 100px;
  padding: 10px;
  border: 10px solid #333;
  margin: 10px;

  /* Color */
  background: #000;
  color: #fff
  
  /* Text */
  font-family: sans-serif;
  font-size: 16px;
  line-height: 1.4;
  text-align: right;

  /* Other */
  cursor: pointer;
}
```
2. Судя по медиазапросам рекомендую почитать о подходе mobile first
3. Можно не заморачиватся в относительных величинах для всего кроме как текста. Тоесть для марджинов, падингов можно смело использовать ```px```
4. Если ещё не сделал, то почитай о сементических тегах которые появились в html5 ```section, footer, header``` и тд
5. Не забывай закидывать html в валидатор, там кстати есть пару ошибок у тебя https://validator.w3.org/nu/
